project:
  type: website

website:
  title: "Skimpy"
  favicon: favicon.ico
  twitter-card: true
  navbar:
    left:
      - href: index.ipynb
        text: Home
      - href: features.ipynb
        text: Features
      - text: "Reference"
        file: reference/index.qmd
      - contributing.qmd
      - code_of_conduct.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml


quartodoc:
  # the name used to import the package you want to create reference docs for
  package: skimpy
  parser: google

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: "Function reference"
      desc: "What skimpy's functions do"
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - skim
        - skim_polars
        - clean_columns
        - generate_test_data
